application: quiz-n-poll
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: favicon.ico

- url: /quiz/.*
  script: djangoappengine.main.application
  login: required

- url: /poll/.*
  script: djangoappengine.main.application
  login: required

- url: /qp_api/poll/status/invalidate/.*
  script: djangoappengine.main.application

- url: /qp_api/.*
  script: djangoappengine.main.application
  login: required

- url: /.*
  script: djangoappengine.main.application
